name: CEStageGenerator
version: '${version}'
main: com.gmail.necnionch.myplugin.cestagegenerator.bukkit.StageGeneratorPlugin
api-version: 1.14
authors: [ Necnion8 ]
depend: [ CommandAPI ]
softdepend: [ Citizens, Multiverse-Core ]
load: STARTUP
